Spawn:
  World: world
  X: 178.5
  Y: 8
  Z: 249.5
  Pitch: 0
  Yaw: 90

# Connects to the MySQL Database
MySQL:
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  useSSL: true